// mobile/src/screens/Home/Views/Library/Import.tsx
import { memo, useCallback, useEffect, useMemo, useState } from 'react'
import { FlatList, ScrollView, TouchableOpacity, View } from 'react-native'

import '@/core/libraryImport'
import {
  clearImport, countImportGroup, finishImport, getImportFromAccount, getImportFromLink, getImportJob, onImportJobChange,
  parseImportFiles, resumeImport, retryImportTrack, setImportAlbumIncluded, setImportArtistIncluded, setImportGroupIncluded,
  setImportTrackIncluded, startImport,
  type ImportAccountPlatform, type ImportFile, type ImportJob, type ImportJobTrack, type ImportSource,
} from '@/utils/libraryImport'
import { SECONDARY_SOURCE_NAMES, isSecondarySource } from '@/utils/secondarySources'
import { selectFile } from '@/utils/fs'
import { createStyle } from '@/utils/tools'
import { useTheme } from '@/store/theme/hook'
import { useI18n } from '@/lang'
import Text from '@/components/common/Text'
import Input from '@/components/common/Input'
import CheckBox from '@/components/common/CheckBox'
import Button from '@/components/common/ButtonPrimary'

// The import of the library of another platform (utils/libraryImport.ts): where from (files, a link, an account),
// what (liked songs, playlists, artists, albums), the songs looked for (in the background), the results checked.

type Tab = 'file' | 'link' | 'account'
const TABS: Tab[] = ['file', 'link', 'account']
const ACCOUNT_PLATFORMS: ImportAccountPlatform[] = ['soundcloud', 'lastfm', 'deezer', 'netease']
const TRACKS_SHOWN = 200

const Pills = <T extends string,>({ items, active, label, onPress }: { items: T[], active: T, label: (item: T) => string, onPress: (item: T) => void }) => {
  const theme = useTheme()
  return (
    <View style={styles.pills}>
      {items.map(item => (
        <TouchableOpacity key={item} activeOpacity={0.7} onPress={() => { onPress(item) }}
          style={{ ...styles.pill, backgroundColor: item == active ? theme['c-button-background'] : 'transparent' }}>
          <Text size={14} color={item == active ? theme['c-primary-font'] : theme['c-font-label']}>{label(item)}</Text>
        </TouchableOpacity>
      ))}
    </View>
  )
}

const Box = ({ children }: { children: React.ReactNode }) => {
  const theme = useTheme()
  return <View style={{ ...styles.box, borderColor: theme['c-border-background'] }}>{children}</View>
}

// where from: files, a link, an account
const SourcePicker = ({ onRead }: { onRead: (source: ImportSource) => void }) => {
  const t = useI18n()
  const theme = useTheme()
  const [tab, setTab] = useState<Tab>('file')
  const [platform, setPlatform] = useState<ImportAccountPlatform>('soundcloud')
  const [linkText, setLinkText] = useState('')
  const [accountText, setAccountText] = useState('')
  const [files, setFiles] = useState<ImportFile[]>([])
  const [reading, setReading] = useState(false)
  const [error, setError] = useState('')

  const read = async(task: () => Promise<ImportSource> | ImportSource) => {
    setReading(true)
    setError('')
    try {
      onRead(await task())
    } catch (err) {
      setError(t('import__error', { msg: (err as Error).message }))
    } finally {
      setReading(false)
    }
  }
  // (one file at a time: more can be added)
  const addFile = async() => {
    try {
      const file = await selectFile({ mimeTypes: ['*/*'] })
      if (file?.data) setFiles(list => [...list.filter(f => f.name != file.name), { name: file.name, text: file.data }])
    } catch (err) {
      setError(t('import__error', { msg: (err as Error).message }))
    }
  }

  return (
    <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
      <Text size={13} color={theme['c-font-label']}>{t('import__desc')}</Text>
      <Pills items={TABS} active={tab} label={item => t(`import__tab_${item}`)} onPress={setTab} />
      {
        tab == 'file'
          ? <Box>
              {files.map(file => <Text key={file.name} size={14}>📄 {file.name}</Text>)}
              <View style={styles.row}>
                <Button onPress={() => { void addFile() }} disabled={reading}>{t(files.length ? 'import__file_add' : 'import__file_btn')}</Button>
                {files.length ? <Button onPress={() => { void read(() => parseImportFiles(files)) }} disabled={reading}>{reading ? t('import__reading') : t('import__read')}</Button> : null}
                {files.length ? <Button onPress={() => { setFiles([]) }} disabled={reading}>{t('import__file_clear')}</Button> : null}
              </View>
              <Text size={12} color={theme['c-font-label']}>{t('import__file_tip')}</Text>
            </Box>
          : tab == 'link'
            ? <Box>
                <View style={styles.inputWrap}><Input value={linkText} onChangeText={setLinkText} placeholder={t('import__link_placeholder')} clearBtn style={styles.input} /></View>
                <View style={styles.row}>
                  <Button onPress={() => { void read(async() => getImportFromLink(linkText)) }} disabled={reading || !linkText.trim()}>{reading ? t('import__reading') : t('import__read')}</Button>
                </View>
                <Text size={12} color={theme['c-font-label']}>{t('import__link_tip')}</Text>
              </Box>
            : <Box>
                <Pills items={ACCOUNT_PLATFORMS} active={platform} label={item => t(`import__platform_${item}`)} onPress={setPlatform} />
                <View style={styles.inputWrap}><Input value={accountText} onChangeText={setAccountText} placeholder={t(`import__account_placeholder_${platform}`)} clearBtn style={styles.input} /></View>
                <View style={styles.row}>
                  <Button onPress={() => { void read(async() => getImportFromAccount(platform, accountText)) }} disabled={reading || !accountText.trim()}>{reading ? t('import__reading') : t('import__read')}</Button>
                </View>
                <Text size={12} color={theme['c-font-label']}>{t(`import__account_tip_${platform}`)}</Text>
              </Box>
      }
      {error ? <Text size={13} color="#e5484d">{error}</Text> : null}
    </ScrollView>
  )
}

const countText = (t: ReturnType<typeof useI18n>, count: number | null) => count == null ? '' : ` (${t('import__songs', { num: count })})`

// what: the liked songs, the playlists, the artists, the albums
const Selection = ({ source, onStart, onBack }: { source: ImportSource, onStart: (selection: Parameters<typeof startImport>[1]) => void, onBack: () => void }) => {
  const t = useI18n()
  const theme = useTheme()
  const [liked, setLiked] = useState(!!source.liked)
  const [playlists, setPlaylists] = useState(() => source.playlists.filter(p => !p.defaultOff).map(p => p.key))
  const [artists, setArtists] = useState(source.artists.length > 0)
  const [albums, setAlbums] = useState(source.albums.length > 0)
  const hasSelection = (liked && !!source.liked) || playlists.length > 0 || (artists && source.artists.length > 0) || (albums && source.albums.length > 0)
  return (
    <ScrollView contentContainerStyle={styles.content}>
      <Box>
        <Text size={15}>{source.title}</Text>
        {source.note ? <Text size={12} color={theme['c-font-label']}>{source.note == 'spotify_limit' ? t('import__spotify_limit') : source.note}</Text> : null}
        {source.liked ? <CheckBox check={liked} onChange={setLiked} label={`${t('import__liked')}${countText(t, source.liked.count)} → ${t('import__to_loved')}`} /> : null}
        {
          source.playlists.length
            ? <>
                <View style={styles.row}>
                  <Text size={14} color={theme['c-font-label']}>{t('import__playlists')} ({source.playlists.length})</Text>
                  <TouchableOpacity onPress={() => { setPlaylists(source.playlists.map(p => p.key)) }}><Text size={13} color={theme['c-primary-font']}>{t('import__select_all')}</Text></TouchableOpacity>
                  <TouchableOpacity onPress={() => { setPlaylists([]) }}><Text size={13} color={theme['c-primary-font']}>{t('import__select_none')}</Text></TouchableOpacity>
                </View>
                {source.playlists.map(p => (
                  <CheckBox key={p.key} check={playlists.includes(p.key)} label={`${p.name}${countText(t, p.count)}`}
                    onChange={check => { setPlaylists(list => check ? [...list, p.key] : list.filter(k => k != p.key)) }} />
                ))}
              </>
            : null
        }
        {source.artists.length ? <CheckBox check={artists} onChange={setArtists} label={`${t('import__artists')} (${source.artists.length})`} /> : null}
        {source.albums.length ? <CheckBox check={albums} onChange={setAlbums} label={`${t('import__albums')} (${source.albums.length})`} /> : null}
      </Box>
      <View style={styles.row}>
        <Button disabled={!hasSelection} onPress={() => { onStart({ liked, playlists, artists, albums }) }}>{t('import__start')}</Button>
        <Button onPress={onBack}>{t('import__back')}</Button>
      </View>
    </ScrollView>
  )
}

const sourceName = (t: ReturnType<typeof useI18n>, source: string) => isSecondarySource(source) ? SECONDARY_SOURCE_NAMES[source] : t(`source_real_${source as LX.OnlineSource}`)

const TrackRow = memo(({ index, item, onRetry }: { index: number, item: ImportJobTrack, onRetry: (index: number) => void }) => {
  const t = useI18n()
  const theme = useTheme()
  const status = item.status == 'notFound' ? t('import__not_found') : item.musicInfo ? sourceName(t, item.musicInfo.source) : '…'
  return (
    <View style={{ ...styles.track, borderTopColor: theme['c-border-background'] }}>
      <View style={styles.trackMain}>
        <CheckBox check={item.include} disabled={!item.musicInfo} onChange={check => { setImportTrackIncluded(index, check) }} marginRight={0}>
          <View style={styles.trackText}>
            <Text size={14} numberOfLines={1}>{item.track.name || item.track.ytId}<Text size={12} color={theme['c-font-label']}>{item.track.singer ? `  ${item.track.singer}` : ''}</Text></Text>
            {item.musicInfo && item.status != 'direct' ? <Text size={11} numberOfLines={1} color={theme['c-font-label']}>→ {item.musicInfo.name} · {item.musicInfo.singer}</Text> : null}
          </View>
        </CheckBox>
      </View>
      <View style={styles.trackSide}>
        <Text size={11} color={item.status == 'notFound' ? '#e5484d' : item.status == 'fallback' ? theme['c-font-label'] : theme['c-primary-font']}>{status}</Text>
        {item.status == 'notFound' || item.status == 'fallback'
          ? <TouchableOpacity onPress={() => { onRetry(index) }}><Text size={11} color={theme['c-primary-font']}>{t('import__retry')}</Text></TouchableOpacity>
          : null}
      </View>
    </View>
  )
})

// a song looked for again with another name / artist
const RetryRow = ({ index, item, onDone }: { index: number, item: ImportJobTrack, onDone: () => void }) => {
  const t = useI18n()
  const theme = useTheme()
  const [name, setName] = useState(item.track.name)
  const [singer, setSinger] = useState(item.track.singer.replace(/、/g, ', '))
  const [searching, setSearching] = useState(false)
  const [message, setMessage] = useState('')
  const search = async() => {
    setSearching(true)
    const status = await retryImportTrack(index, name, singer).catch(() => 'notFound')
    setSearching(false)
    if (status == 'notFound') setMessage(t('import__not_found'))
    else onDone()
  }
  return (
    <View style={{ ...styles.retry, borderColor: theme['c-border-background'] }}>
      <View style={styles.inputWrap}><Input value={name} onChangeText={setName} placeholder={t('import__retry_name')} style={styles.input} /></View>
      <View style={styles.inputWrap}><Input value={singer} onChangeText={setSinger} placeholder={t('import__retry_singer')} style={styles.input} /></View>
      <View style={styles.row}>
        <Button disabled={searching || !name.trim()} onPress={() => { void search() }}>{searching ? t('import__reading') : t('import__retry_go')}</Button>
        <Button onPress={onDone}>{t('import__back')}</Button>
        {message ? <Text size={12} color="#e5484d">{message}</Text> : null}
      </View>
    </View>
  )
}

type ReviewRow =
  | { type: 'group', key: string, groupIndex: number }
  | { type: 'track', key: string, index: number }
  | { type: 'retry', key: string, index: number }
  | { type: 'more', key: string, groupIndex: number, num: number }
  | { type: 'title', key: string, text: string }
  | { type: 'artist', key: string, index: number }
  | { type: 'album', key: string, index: number }

// the results: each list with its songs, the artists, the albums
const Review = ({ job }: { job: ImportJob }) => {
  const t = useI18n()
  const theme = useTheme()
  const [openGroups, setOpenGroups] = useState<number[]>([0])
  const [shownAll, setShownAll] = useState<number[]>([])
  const [onlyNotFound, setOnlyNotFound] = useState(false)
  const [retryIndex, setRetryIndex] = useState<number | null>(null)
  const counts = useMemo(() => job.groups.map(group => countImportGroup(job, group)), [job])
  const included = useMemo(() => {
    const songs = new Set<number>()
    for (const group of job.groups) for (const index of group.tracks) if (job.tracks[index].include && job.tracks[index].musicInfo) songs.add(index)
    return songs.size + job.artists.filter(a => a.include).length + job.albums.filter(a => a.include && a.result).length
  }, [job])

  const rows = useMemo(() => {
    const list: ReviewRow[] = []
    job.groups.forEach((group, groupIndex) => {
      list.push({ type: 'group', key: `g${groupIndex}`, groupIndex })
      if (!openGroups.includes(groupIndex)) return
      const indexes = onlyNotFound ? group.tracks.filter(index => job.tracks[index].status == 'notFound') : group.tracks
      const shown = shownAll.includes(groupIndex) ? indexes : indexes.slice(0, TRACKS_SHOWN)
      for (const index of shown) {
        list.push({ type: 'track', key: `t${groupIndex}_${index}`, index })
        if (retryIndex == index) list.push({ type: 'retry', key: `r${groupIndex}_${index}`, index })
      }
      if (shown.length < indexes.length) list.push({ type: 'more', key: `m${groupIndex}`, groupIndex, num: indexes.length - shown.length })
    })
    if (job.artists.length) {
      list.push({ type: 'title', key: 'artists', text: `${t('import__artists')} (${job.artists.length})` })
      job.artists.forEach((_, index) => list.push({ type: 'artist', key: `a${index}`, index }))
    }
    if (job.albums.length) {
      list.push({ type: 'title', key: 'albums', text: `${t('import__albums')} (${job.albums.length})` })
      job.albums.forEach((_, index) => list.push({ type: 'album', key: `al${index}`, index }))
    }
    return list
  }, [job, openGroups, shownAll, onlyNotFound, retryIndex, t])

  const toggleGroup = useCallback((groupIndex: number) => {
    setOpenGroups(list => list.includes(groupIndex) ? list.filter(i => i != groupIndex) : [...list, groupIndex])
  }, [])
  const closeRetry = useCallback(() => { setRetryIndex(null) }, [])

  const renderItem = ({ item: row }: { item: ReviewRow }) => {
    switch (row.type) {
      case 'group': {
        const group = job.groups[row.groupIndex]
        const count = counts[row.groupIndex]
        return (
          <View style={styles.groupHead}>
            <CheckBox check={count.included > 0} onChange={check => { setImportGroupIncluded(row.groupIndex, check) }} marginRight={0} />
            <TouchableOpacity style={styles.groupName} onPress={() => { toggleGroup(row.groupIndex) }}>
              <Text size={15} numberOfLines={1}>{openGroups.includes(row.groupIndex) ? '▾ ' : '▸ '}{group.kind == 'liked' ? `${t('import__liked')} → ${t('import__to_loved')}` : group.name}</Text>
              <Text size={12} color={theme['c-font-label']}>{t('import__counts', { found: count.found, fallback: count.fallback, notFound: count.notFound })}</Text>
            </TouchableOpacity>
          </View>
        )
      }
      case 'track': return <TrackRow index={row.index} item={job.tracks[row.index]} onRetry={setRetryIndex} />
      case 'retry': return <RetryRow index={row.index} item={job.tracks[row.index]} onDone={closeRetry} />
      case 'more':
        return (
          <TouchableOpacity style={styles.more} onPress={() => { setShownAll(list => [...list, row.groupIndex]) }}>
            <Text size={13} color={theme['c-primary-font']}>{t('import__show_more', { num: row.num })}</Text>
          </TouchableOpacity>
        )
      case 'title': return <Text size={15} style={styles.title}>{row.text}</Text>
      case 'artist': {
        const item = job.artists[row.index]
        return <CheckBox check={item.include} label={item.artist.name} onChange={check => { setImportArtistIncluded(row.index, check) }} />
      }
      case 'album': {
        const item = job.albums[row.index]
        return (
          <View style={{ ...styles.track, borderTopColor: theme['c-border-background'] }}>
            <View style={styles.trackMain}>
              <CheckBox check={item.include} disabled={!item.result} onChange={check => { setImportAlbumIncluded(row.index, check) }} marginRight={0}>
                <View style={styles.trackText}>
                  <Text size={14} numberOfLines={1}>{item.album.name}<Text size={12} color={theme['c-font-label']}>{item.album.artist ? `  ${item.album.artist}` : ''}</Text></Text>
                </View>
              </CheckBox>
            </View>
            <Text size={11} color={item.result ? theme['c-primary-font'] : '#e5484d'}>{item.result ? sourceName(t, item.result.source) : t('import__not_found')}</Text>
          </View>
        )
      }
    }
  }

  return (
    <FlatList
      data={rows}
      keyExtractor={row => row.key}
      renderItem={renderItem}
      contentContainerStyle={styles.content}
      keyboardShouldPersistTaps="handled"
      ListHeaderComponent={
        <View style={styles.reviewHead}>
          <Text size={15}>{t('import__review')} · {job.title}</Text>
          <CheckBox check={onlyNotFound} label={t('import__only_not_found')} onChange={setOnlyNotFound} />
          {job.error ? <Text size={13} color="#e5484d">{job.error}</Text> : null}
        </View>
      }
      ListFooterComponent={
        <View style={{ ...styles.row, ...styles.footer }}>
          <Button disabled={job.stage == 'importing' || !included} onPress={() => { void finishImport() }}>
            {job.stage == 'importing' ? t('import__importing') : t('import__finish', { num: included })}
          </Button>
          <Button disabled={job.stage == 'importing'} onPress={clearImport}>{t('import__cancel')}</Button>
        </View>
      }
    />
  )
}

export default () => {
  const t = useI18n()
  const theme = useTheme()
  const [preview, setPreview] = useState<ImportSource | null>(null)
  const [job, setJob] = useState<ImportJob | null>(() => getImportJob())
  useEffect(() => {
    const off = onImportJobChange(setJob)
    void resumeImport()
    return off
  }, [])

  if (!job) {
    if (!preview) return <SourcePicker onRead={setPreview} />
    return (
      <Selection
        source={preview}
        onBack={() => { setPreview(null) }}
        onStart={selection => {
          void startImport(preview, selection)
          setPreview(null)
        }}
      />
    )
  }
  if (job.stage == 'loading' || job.stage == 'matching') {
    const progress = job.total ? Math.min(100, Math.round(job.done / job.total * 100)) : 0
    return (
      <ScrollView contentContainerStyle={styles.content}>
        <Box>
          <Text size={15}>{job.title}</Text>
          <Text size={14}>{job.stage == 'loading' ? t('import__loading') : t('import__matching', { done: Math.min(job.done, job.total), total: job.total })}</Text>
          <View style={{ ...styles.bar, backgroundColor: theme['c-border-background'] }}>
            <View style={{ ...styles.barFill, width: `${progress}%`, backgroundColor: theme['c-primary'] }} />
          </View>
          <Text size={12} color={theme['c-font-label']}>{t('import__background_tip')}</Text>
        </Box>
        <View style={styles.row}>
          <Button onPress={clearImport}>{t('import__cancel')}</Button>
        </View>
      </ScrollView>
    )
  }
  if (job.stage == 'review' || job.stage == 'importing') return <Review job={job} />
  if (job.stage == 'done' && job.result) {
    return (
      <ScrollView contentContainerStyle={styles.content}>
        <Box>
          <Text size={15}>{t('import__done')}</Text>
          <Text size={14}>{t('import__result', job.result)}</Text>
          {job.result.skipped ? <Text size={12} color={theme['c-font-label']}>{t('import__skipped', { num: job.result.skipped })}</Text> : null}
        </Box>
        <View style={styles.row}>
          <Button onPress={clearImport}>{t('import__again')}</Button>
        </View>
      </ScrollView>
    )
  }
  return (
    <ScrollView contentContainerStyle={styles.content}>
      <Text size={14} color="#e5484d">{t('import__failed', { msg: job.error ?? '' })}</Text>
      <View style={styles.row}>
        <Button onPress={clearImport}>{t('import__back')}</Button>
      </View>
    </ScrollView>
  )
}

const styles = createStyle({
  content: {
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 30,
    gap: 12,
  },
  pills: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  pill: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 16,
  },
  box: {
    gap: 10,
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
  },
  row: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 10,
  },
  // (the input grows to the space it is given)
  inputWrap: {
    height: 42,
    flexDirection: 'row',
  },
  input: {
    height: 42,
    borderRadius: 6,
    paddingHorizontal: 10,
  },
  bar: {
    height: 6,
    borderRadius: 3,
    overflow: 'hidden',
  },
  barFill: {
    height: '100%',
  },
  reviewHead: {
    gap: 6,
    marginBottom: 6,
  },
  groupHead: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 10,
    paddingBottom: 4,
  },
  groupName: {
    flex: 1,
    gap: 2,
  },
  track: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    borderTopWidth: 1,
    gap: 6,
  },
  trackMain: {
    flex: 1,
    minWidth: 0,
  },
  trackText: {
    flexShrink: 1,
  },
  trackSide: {
    alignItems: 'flex-end',
    gap: 2,
  },
  retry: {
    gap: 8,
    padding: 10,
    borderWidth: 1,
    borderRadius: 8,
    marginBottom: 6,
  },
  more: {
    paddingVertical: 10,
  },
  title: {
    marginTop: 14,
    marginBottom: 4,
  },
  footer: {
    marginTop: 16,
  },
})

// desktop/src/renderer/views/Import/index.vue
<template>
  <div :class="[$style.container, 'scroll']">
    <!-- one page for the import of other platforms and the sync of the devices -->
    <div :class="$style.header">
      <button
        v-for="tab in PAGE_TABS" :key="tab" type="button"
        :class="[$style.pageTab, { [$style.active]: tab == pageTab }]" @click="setPageTab(tab)"
      >
        {{ $t(tab == 'import' ? 'import__title' : 'setting__sync') }}
      </button>
    </div>

    <!-- the sync of the devices (the same as in the settings) -->
    <template v-if="pageTab == 'sync'">
      <p v-if="!isServerOn" :class="$style.desc">{{ $t('sync__desktop_tip') }}</p>
      <!-- pairing a phone: the code, big (sync on, server mode) -->
      <section v-if="isServerOn" :class="$style.pairCard">
        <div :class="$style.pairMain">
          <span :class="$style.pairLabel">{{ $t('sync__pair_code') }}</span>
          <strong :class="$style.pairCode">{{ pairCode }}</strong>
          <span :class="$style.pairHint">{{ $t('sync__pair_hint', { name: computerName }) }}</span>
        </div>
        <div :class="$style.pairSide">
          <base-btn min :disabled="!sync.server.status.status" @click="refreshCode">{{ $t('setting__sync_server_refresh_code') }}</base-btn>
          <span :class="$style.pairDevices">{{ connectedDevices ? $t('sync__pair_connected', { devices: connectedDevices }) : $t('sync__pair_none') }}</span>
        </div>
      </section>
      <!-- the settings of the sync: under "Advanced" once it runs (the code is above) -->
      <!-- the main settings (enable, how new devices sync), the others under "Advanced" -->
      <dl :class="$style.sync">
        <SettingSync part="main" />
      </dl>
      <button type="button" :class="$style.advancedBtn" @click="showAdvanced = !showAdvanced">
        {{ $t('sync__advanced') }} {{ showAdvanced ? '▾' : '▸' }}
      </button>
      <dl v-if="showAdvanced" :class="$style.sync">
        <SettingSync part="advanced" />
      </dl>
    </template>

    <template v-else>
    <!-- where from -->
    <template v-if="!job && !preview">
      <p :class="$style.desc">{{ $t('import__desc') }}</p>
      <div :class="$style.tabs">
        <button
          v-for="tab in TABS" :key="tab" type="button"
          :class="[$style.tabBtn, { [$style.active]: tab == activeTab }]" @click="activeTab = tab"
        >
          {{ $t(`import__tab_${tab}`) }}
        </button>
      </div>
      <section v-if="activeTab == 'file'" :class="$style.box">
        <div :class="$style.row">
          <base-btn :disabled="reading" @click="fileInput.click()">{{ reading ? $t('import__reading') : $t('import__file_btn') }}</base-btn>
          <input ref="fileInput" type="file" multiple accept=".csv,.tsv,.txt,.json" :class="$style.hidden" @change="handleFiles">
        </div>
        <p :class="$style.tip">{{ $t('import__file_tip') }}</p>
      </section>
      <section v-else-if="activeTab == 'link'" :class="$style.box">
        <div :class="$style.row">
          <base-input v-model.trim="linkText" :class="$style.input" :placeholder="$t('import__link_placeholder')" @submit="readLink" />
          <base-btn :disabled="reading || !linkText" @click="readLink">{{ reading ? $t('import__reading') : $t('import__read') }}</base-btn>
        </div>
        <p :class="$style.tip">{{ $t('import__link_tip') }}</p>
      </section>
      <section v-else :class="$style.box">
        <div :class="$style.tabs">
          <button
            v-for="platform in ACCOUNT_PLATFORMS" :key="platform" type="button"
            :class="[$style.tabBtn, { [$style.active]: platform == accountPlatform }]" @click="accountPlatform = platform"
          >
            {{ $t(`import__platform_${platform}`) }}
          </button>
        </div>
        <div :class="$style.row">
          <base-input v-model.trim="accountText" :class="$style.input" :placeholder="$t(`import__account_placeholder_${accountPlatform}`)" @submit="readAccount" />
          <base-btn :disabled="reading || !accountText" @click="readAccount">{{ reading ? $t('import__reading') : $t('import__read') }}</base-btn>
        </div>
        <p :class="$style.tip">{{ $t(`import__account_tip_${accountPlatform}`) }}</p>
      </section>
      <p v-if="error" :class="$style.error">{{ error }}</p>
    </template>

    <!-- what -->
    <template v-else-if="!job">
      <section :class="$style.box">
        <h3>{{ preview.title }}</h3>
        <p v-if="preview.note" :class="$style.note">{{ $t(`import__${preview.note}`) }}</p>
        <base-checkbox
          v-if="preview.liked" id="import_liked" :model-value="selection.liked"
          :label="`${$t('import__liked')}${countText(preview.liked.count)} → ${$t('import__to_loved')}`" @update:model-value="selection.liked = $event"
        />
        <template v-if="preview.playlists.length">
          <div :class="$style.groupTitle">
            <span>{{ $t('import__playlists') }} ({{ preview.playlists.length }})</span>
            <button type="button" :class="$style.link" @click="selectAllPlaylists(true)">{{ $t('import__select_all') }}</button>
            <button type="button" :class="$style.link" @click="selectAllPlaylists(false)">{{ $t('import__select_none') }}</button>
          </div>
          <ul :class="$style.playlists">
            <li v-for="playlist in preview.playlists" :key="playlist.key">
              <base-checkbox
                :id="`import_pl_${playlist.key}`" :model-value="selection.playlists.includes(playlist.key)"
                :label="`${playlist.name}${countText(playlist.count)}`" @update:model-value="togglePlaylist(playlist.key, $event)"
              />
            </li>
          </ul>
        </template>
        <base-checkbox
          v-if="preview.artists.length" id="import_artists" :model-value="selection.artists"
          :label="`${$t('import__artists')} (${preview.artists.length})`" @update:model-value="selection.artists = $event"
        />
        <base-checkbox
          v-if="preview.albums.length" id="import_albums" :model-value="selection.albums"
          :label="`${$t('import__albums')} (${preview.albums.length})`" @update:model-value="selection.albums = $event"
        />
      </section>
      <div :class="$style.actions">
        <base-btn :disabled="!hasSelection" @click="startJob">{{ $t('import__start') }}</base-btn>
        <base-btn @click="preview = null">{{ $t('import__back') }}</base-btn>
      </div>
    </template>

    <!-- looking for the songs -->
    <template v-else-if="job.stage == 'loading' || job.stage == 'matching'">
      <section :class="$style.box">
        <h3>{{ job.title }}</h3>
        <p>{{ job.stage == 'loading' ? $t('import__loading') : $t('import__matching', { done: Math.min(job.done, job.total), total: job.total }) }}</p>
        <div :class="$style.bar"><div :class="$style.barFill" :style="{ width: `${progress}%` }" /></div>
        <p :class="$style.tip">{{ $t('import__background_tip') }}</p>
      </section>
      <div :class="$style.actions">
        <base-btn @click="clearImport">{{ $t('import__cancel') }}</base-btn>
      </div>
    </template>

    <!-- the results -->
    <template v-else-if="job.stage == 'review' || job.stage == 'importing'">
      <div :class="$style.reviewHead">
        <h3>{{ $t('import__review') }} · {{ job.title }}</h3>
        <base-checkbox id="import_only_not_found" :model-value="onlyNotFound" :label="$t('import__only_not_found')" @update:model-value="onlyNotFound = $event" />
      </div>
      <p v-if="job.error" :class="$style.error">{{ job.error }}</p>
      <section v-for="(group, groupIndex) in job.groups" :key="groupIndex" :class="$style.box">
        <div :class="$style.groupHead">
          <base-checkbox
            :id="`import_group_${groupIndex}`" :model-value="groupCounts[groupIndex].included > 0" :aria-label="group.name"
            @update:model-value="setImportGroupIncluded(groupIndex, $event)"
          />
          <button type="button" :class="$style.groupName" @click="toggleOpen(groupIndex)">
            <strong>{{ group.kind == 'liked' ? `${$t('import__liked')} → ${$t('import__to_loved')}` : group.name }}</strong>
            <span :class="$style.counts">
              {{ $t('import__counts', { found: groupCounts[groupIndex].found, fallback: groupCounts[groupIndex].fallback, notFound: groupCounts[groupIndex].notFound }) }}
            </span>
            <span :class="$style.arrow">{{ openGroups.includes(groupIndex) ? '▾' : '▸' }}</span>
          </button>
        </div>
        <ul v-if="openGroups.includes(groupIndex)" :class="$style.tracks">
          <li v-for="index in visibleTracks(groupIndex)" :key="index" :class="$style.track">
            <base-checkbox
              :id="`import_t_${index}`" :model-value="job.tracks[index].include" :disabled="!job.tracks[index].musicInfo"
              :aria-label="job.tracks[index].track.name" @update:model-value="setImportTrackIncluded(index, $event)"
            />
            <div :class="$style.trackText">
              <p :class="$style.trackName">{{ job.tracks[index].track.name || job.tracks[index].track.ytId }}<span v-if="job.tracks[index].track.singer"> · {{ job.tracks[index].track.singer }}</span></p>
              <p v-if="job.tracks[index].musicInfo && job.tracks[index].status != 'direct'" :class="$style.trackMatch">
                → {{ job.tracks[index].musicInfo.name }} · {{ job.tracks[index].musicInfo.singer }}
              </p>
            </div>
            <span :class="[$style.chip, $style[job.tracks[index].status]]">{{ statusLabel(job.tracks[index]) }}</span>
            <button v-if="job.tracks[index].status == 'notFound' || job.tracks[index].status == 'fallback'" type="button" :class="$style.link" @click="startRetry(index)">{{ $t('import__retry') }}</button>
          </li>
          <li v-if="hiddenCount(groupIndex)" :class="$style.more">
            <button type="button" :class="$style.link" @click="showAll(groupIndex)">{{ $t('import__show_more', { num: hiddenCount(groupIndex) }) }}</button>
          </li>
        </ul>
      </section>
      <section v-if="job.artists.length" :class="$style.box">
        <div :class="$style.groupTitle"><span>{{ $t('import__artists') }} ({{ job.artists.length }})</span></div>
        <ul :class="$style.artists">
          <li v-for="(item, index) in job.artists" :key="index">
            <base-checkbox :id="`import_a_${index}`" :model-value="item.include" :label="item.artist.name" @update:model-value="setImportArtistIncluded(index, $event)" />
          </li>
        </ul>
      </section>
      <section v-if="job.albums.length" :class="$style.box">
        <div :class="$style.groupTitle"><span>{{ $t('import__albums') }} ({{ job.albums.length }})</span></div>
        <ul :class="$style.tracks">
          <li v-for="(item, index) in job.albums" :key="index" :class="$style.track">
            <base-checkbox
              :id="`import_al_${index}`" :model-value="item.include" :disabled="!item.result" :aria-label="item.album.name"
              @update:model-value="setImportAlbumIncluded(index, $event)"
            />
            <div :class="$style.trackText">
              <p :class="$style.trackName">{{ item.album.name }}<span v-if="item.album.artist"> · {{ item.album.artist }}</span></p>
            </div>
            <span :class="[$style.chip, $style[item.result ? 'found' : 'notFound']]">{{ item.result ? sourceName(item.result.source) : $t('import__not_found') }}</span>
          </li>
        </ul>
      </section>
      <div :class="$style.actions">
        <base-btn :disabled="job.stage == 'importing' || !includedCount" @click="handleFinish">
          {{ job.stage == 'importing' ? $t('import__importing') : $t('import__finish', { num: includedCount }) }}
        </base-btn>
        <base-btn :disabled="job.stage == 'importing'" @click="clearImport">{{ $t('import__cancel') }}</base-btn>
      </div>
    </template>

    <!-- done -->
    <template v-else-if="job.stage == 'done'">
      <section :class="$style.box">
        <h3>{{ $t('import__done') }}</h3>
        <p>{{ $t('import__result', job.result) }}</p>
        <p v-if="job.result.skipped" :class="$style.tip">{{ $t('import__skipped', { num: job.result.skipped }) }}</p>
      </section>
      <div :class="$style.actions">
        <base-btn @click="openLibrary">{{ $t('import__open_library') }}</base-btn>
        <base-btn @click="clearImport">{{ $t('import__again') }}</base-btn>
      </div>
    </template>

    <template v-else>
      <p :class="$style.error">{{ $t('import__failed', { msg: job.error ?? '' }) }}</p>
      <div :class="$style.actions">
        <base-btn @click="clearImport">{{ $t('import__back') }}</base-btn>
      </div>
    </template>
    </template>

    <material-modal :show="retryIndex != null" teleport="#view" width="420px" @close="retryIndex = null">
      <main :class="$style.retry">
        <h2>{{ $t('import__retry') }}</h2>
        <base-input v-model="retryName" :class="$style.input" :placeholder="$t('import__retry_name')" @submit="handleRetry" />
        <base-input v-model="retrySinger" :class="$style.input" :placeholder="$t('import__retry_singer')" @submit="handleRetry" />
        <p v-if="retryMessage" :class="$style.tip">{{ retryMessage }}</p>
        <div :class="$style.actions">
          <base-btn :disabled="retrying || !retryName.trim()" @click="handleRetry">{{ retrying ? $t('import__reading') : $t('import__retry_go') }}</base-btn>
        </div>
      </main>
    </material-modal>
  </div>
</template>

<script setup>
import { computed, markRaw, onBeforeUnmount, reactive, ref, shallowRef } from '@common/utils/vueTools'
import { useRoute, useRouter } from '@common/utils/vueRouter'
import SettingSync from '@renderer/views/Setting/components/SettingSync/index.vue'
import { sourceNames, sync } from '@renderer/store'
import { appSetting } from '@renderer/store/setting'
import { sendSyncAction } from '@renderer/utils/ipc'
import { hostname } from 'node:os'
import '@renderer/core/libraryImport'
import {
  clearImport,
  countImportGroup,
  finishImport,
  getImportFromAccount,
  getImportFromLink,
  getImportJob,
  onImportJobChange,
  parseImportFiles,
  resumeImport,
  retryImportTrack,
  setImportAlbumIncluded,
  setImportArtistIncluded,
  setImportGroupIncluded,
  setImportTrackIncluded,
  startImport,
} from '@renderer/utils/libraryImport'
import { SECONDARY_SOURCE_NAMES } from '@renderer/utils/secondarySources'

// The import of the library of another platform (utils/libraryImport.ts): where from (files, a link, an account),
// what (liked songs, playlists, artists, albums), the songs looked for (in the background), the results checked.

const TABS = ['file', 'link', 'account']
const ACCOUNT_PLATFORMS = ['soundcloud', 'lastfm', 'deezer', 'netease']
const TRACKS_SHOWN = 200

const router = useRouter()
const route = useRoute()

// the code to pair a phone (shown big), the name of this computer (the phones show it)
const isServerOn = computed(() => appSetting['sync.enable'] && appSetting['sync.mode'] == 'server')
const pairCode = computed(() => String(sync.server.status.code || '------').replace(/^(\d{3})(\d{3})$/, '$1 $2'))
const computerName = hostname()
const showAdvanced = ref(false)
const connectedDevices = computed(() => sync.server.status.devices.map(d => d.deviceName).join(', '))
const refreshCode = () => {
  void sendSyncAction({ action: 'generate_code' })
}

// the tabs of the page: the import, the sync (kept in the address: ?tab=sync)
const PAGE_TABS = ['import', 'sync']
const pageTab = computed(() => route.query.tab == 'sync' ? 'sync' : 'import')
const setPageTab = (tab) => {
  void router.replace({ path: route.path, query: tab == 'sync' ? { tab } : {} })
}

const activeTab = ref('file')
const accountPlatform = ref('soundcloud')
const linkText = ref('')
const accountText = ref('')
const reading = ref(false)
const error = ref('')
const fileInput = ref(null)

// what was read, what is chosen
const preview = shallowRef(null)
const selection = reactive({ liked: true, playlists: [], artists: true, albums: true })
const setPreview = (source) => {
  preview.value = markRaw(source)
  selection.liked = !!source.liked
  selection.playlists = source.playlists.filter(p => !p.defaultOff).map(p => p.key)
  selection.artists = source.artists.length > 0
  selection.albums = source.albums.length > 0
}
const read = async(task) => {
  reading.value = true
  error.value = ''
  try {
    setPreview(await task())
  } catch (err) {
    error.value = window.i18n.t('import__error', { msg: err.message })
  } finally {
    reading.value = false
  }
}
const handleFiles = async(event) => {
  const files = Array.from(event.target.files ?? [])
  event.target.value = ''
  if (!files.length) return
  await read(async() => parseImportFiles(await Promise.all(files.map(async file => ({ name: file.name, text: await file.text() })))))
}
const readLink = async() => {
  if (linkText.value) await read(async() => getImportFromLink(linkText.value))
}
const readAccount = async() => {
  if (accountText.value) await read(async() => getImportFromAccount(accountPlatform.value, accountText.value))
}

const countText = (count) => count == null ? '' : ` (${window.i18n.t('import__songs', { num: count })})`
const togglePlaylist = (key, checked) => {
  selection.playlists = checked ? [...selection.playlists, key] : selection.playlists.filter(k => k != key)
}
const selectAllPlaylists = (checked) => {
  selection.playlists = checked ? preview.value.playlists.map(p => p.key) : []
}
const hasSelection = computed(() => {
  const source = preview.value
  if (!source) return false
  return (selection.liked && !!source.liked) || selection.playlists.length > 0 || (selection.artists && source.artists.length > 0) || (selection.albums && source.albums.length > 0)
})
const startJob = () => {
  const source = preview.value
  if (!source) return
  void startImport(source, { liked: selection.liked, playlists: [...selection.playlists], artists: selection.artists, albums: selection.albums }).catch(err => {
    error.value = err.message
  })
  preview.value = null
}

// the import (it goes on when the page is left)
const job = shallowRef(getImportJob())
const offJob = onImportJobChange(value => {
  job.value = value ? markRaw(value) : null
})
onBeforeUnmount(offJob)
void resumeImport()

const progress = computed(() => job.value?.total ? Math.min(100, Math.round(job.value.done / job.value.total * 100)) : 0)
const groupCounts = computed(() => job.value ? job.value.groups.map(group => countImportGroup(job.value, group)) : [])
const includedCount = computed(() => {
  const current = job.value
  if (!current) return 0
  const songs = new Set()
  for (const group of current.groups) for (const index of group.tracks) if (current.tracks[index].include && current.tracks[index].musicInfo) songs.add(index)
  return songs.size + current.artists.filter(a => a.include).length + current.albums.filter(a => a.include && a.result).length
})

const openGroups = ref([0])
const toggleOpen = (index) => {
  openGroups.value = openGroups.value.includes(index) ? openGroups.value.filter(i => i != index) : [...openGroups.value, index]
}
const onlyNotFound = ref(false)
const shownAll = ref([])
const groupTracks = (groupIndex) => {
  const current = job.value
  const indexes = current.groups[groupIndex].tracks
  return onlyNotFound.value ? indexes.filter(index => current.tracks[index].status == 'notFound') : indexes
}
const visibleTracks = (groupIndex) => {
  const indexes = groupTracks(groupIndex)
  return shownAll.value.includes(groupIndex) ? indexes : indexes.slice(0, TRACKS_SHOWN)
}
const hiddenCount = (groupIndex) => shownAll.value.includes(groupIndex) ? 0 : Math.max(0, groupTracks(groupIndex).length - TRACKS_SHOWN)
const showAll = (groupIndex) => {
  shownAll.value = [...shownAll.value, groupIndex]
}

const sourceName = (source) => SECONDARY_SOURCE_NAMES[source] ?? sourceNames.value[source] ?? source
const statusLabel = (item) => {
  switch (item.status) {
    case 'notFound': return window.i18n.t('import__not_found')
    case 'pending': return '…'
    default: return item.musicInfo ? sourceName(item.musicInfo.source) : ''
  }
}

// a song looked for again with another name / artist
const retryIndex = ref(null)
const retryName = ref('')
const retrySinger = ref('')
const retrying = ref(false)
const retryMessage = ref('')
const startRetry = (index) => {
  const track = job.value.tracks[index].track
  retryIndex.value = index
  retryName.value = track.name
  retrySinger.value = track.singer.replaceAll('、', ', ')
  retryMessage.value = ''
}
const handleRetry = async() => {
  if (retryIndex.value == null || !retryName.value.trim()) return
  retrying.value = true
  try {
    const status = await retryImportTrack(retryIndex.value, retryName.value, retrySinger.value)
    if (status == 'notFound') retryMessage.value = window.i18n.t('import__not_found')
    else retryIndex.value = null
  } finally {
    retrying.value = false
  }
}

const handleFinish = () => {
  void finishImport()
}
const openLibrary = () => {
  void router.push({ path: '/library' })
}
</script>

<style lang="less" module>
@import '@renderer/assets/styles/layout.less';

.container {
  height: 100%;
  padding: 15px 18px 25px;
  display: flex;
  flex-flow: column nowrap;
  gap: 14px;
}
.container > * {
  flex: none;
}
.header {
  display: flex;
  align-items: center;
  gap: 6px;
}
.pageTab {
  border: none;
  background: transparent;
  padding: 4px 4px 6px;
  margin-right: 14px;
  font-size: 18px;
  color: var(--color-font-label);
  cursor: pointer;
  border-bottom: 2px solid transparent;
  &:hover {
    color: var(--color-font);
  }
  &.active {
    color: var(--color-font);
    border-bottom-color: var(--color-primary);
  }
}
.advancedBtn {
  align-self: flex-start;
  border: none;
  background: transparent;
  padding: 4px 0;
  margin-bottom: 10px;
  font-size: 13px;
  color: var(--color-font-label);
  cursor: pointer;
  &:hover {
    color: var(--color-font);
  }
}
.pairCard {
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: 16px;
  padding: 18px 22px;
  margin-bottom: 18px;
  border-radius: 12px;
  background-color: var(--color-primary-background-hover);
}
.pairMain {
  display: flex;
  flex-flow: column nowrap;
  gap: 4px;
}
.pairLabel {
  font-size: 12px;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: var(--color-font-label);
}
.pairCode {
  font-size: 40px;
  line-height: 1.1;
  letter-spacing: 0.08em;
  font-variant-numeric: tabular-nums;
  color: var(--color-primary-font);
  user-select: text;
}
.pairHint {
  font-size: 12px;
  color: var(--color-font-label);
}
.pairSide {
  display: flex;
  flex-flow: column nowrap;
  align-items: flex-end;
  gap: 8px;
}
.pairDevices {
  font-size: 12px;
  color: var(--color-font-label);
  max-width: 280px;
  text-align: right;
}
// the sync settings: styled like the settings page
.sync {
  :global {
    dt {
      padding: 3px 7px;
      margin-top: 6px;
      margin-bottom: 15px;
      font-size: 15px;
      border-left: 5px solid var(--color-primary-alpha-700);
      + dd h3 {
        margin-top: 0;
      }
    }
    dd {
      padding-right: 10px;
      > div {
        margin-left: 16px;
      }
      + dd {
        h3 {
          margin-top: 14px;
        }
      }
      .checkbox,
      .radio {
        font-size: 14px;
      }
    }
    h3 {
      padding-bottom: 8px;
      font-size: 13px;
    }
    .p {
      padding: 3px 0;
      line-height: 1.3;
      .btn {
        + .btn {
          margin-left: 10px;
        }
      }
    }
    .help-btn {
      padding: 0;
      margin: 0 0.4em;
      color: var(--color-button-font);
      cursor: pointer;
      background: none;
      border: none;
      transition: opacity 0.2s ease;
      &:hover {
        opacity: 0.7;
      }
    }
  }
}
.desc, .tip {
  font-size: 12px;
  line-height: 1.6;
  color: var(--color-font-label);
}
.note {
  font-size: 12px;
  line-height: 1.5;
  color: var(--color-font);
  padding: 6px 10px;
  border-radius: 6px;
  background-color: var(--color-primary-background-hover);
}
.error {
  font-size: 13px;
  color: #e5484d;
  word-break: break-word;
}
.hidden {
  display: none;
}
.tabs {
  display: flex;
  gap: 4px;
  flex-wrap: wrap;
}
.tabBtn {
  border: none;
  background: transparent;
  padding: 5px 12px;
  border-radius: 14px;
  font-size: 13px;
  color: var(--color-font-label);
  cursor: pointer;
  &:hover {
    color: var(--color-font);
  }
  &.active {
    color: var(--color-primary-font);
    background-color: var(--color-primary-background-hover);
  }
}
.box {
  display: flex;
  flex-flow: column nowrap;
  gap: 10px;
  padding: 14px 16px;
  border-radius: 10px;
  background-color: var(--color-primary-light-600-alpha-900, rgba(128, 128, 128, 0.08));
  h3 {
    font-size: 14px;
    color: var(--color-font);
  }
  p {
    font-size: 13px;
    color: var(--color-font);
  }
}
.row {
  display: flex;
  gap: 8px;
  align-items: center;
}
.input {
  flex: auto;
  padding: 8px;
  color: var(--color-font);
}
.actions {
  display: flex;
  gap: 10px;
}
.link {
  border: none;
  background: transparent;
  padding: 0 4px;
  font-size: 12px;
  color: var(--color-primary-font);
  cursor: pointer;
  white-space: nowrap;
  &:hover {
    text-decoration: underline;
  }
}
.groupTitle {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 13px;
  color: var(--color-font);
}
.playlists {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
  gap: 6px 16px;
  max-height: 320px;
  overflow-y: auto;
}
.artists {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
  gap: 6px 16px;
  max-height: 260px;
  overflow-y: auto;
}
.bar {
  height: 6px;
  border-radius: 3px;
  overflow: hidden;
  background-color: var(--color-primary-background-hover);
}
.barFill {
  height: 100%;
  background-color: var(--color-primary);
  transition: width 0.3s ease;
}
.reviewHead {
  display: flex;
  align-items: center;
  gap: 16px;
  h3 {
    flex: auto;
    font-size: 14px;
    color: var(--color-font);
  }
}
.groupHead {
  display: flex;
  align-items: center;
  gap: 6px;
}
.groupName {
  flex: auto;
  display: flex;
  align-items: center;
  gap: 10px;
  border: none;
  background: transparent;
  padding: 0;
  cursor: pointer;
  color: var(--color-font);
  font-size: 13px;
  text-align: left;
}
.counts {
  flex: auto;
  font-size: 12px;
  color: var(--color-font-label);
}
.arrow {
  color: var(--color-font-label);
}
.tracks {
  display: flex;
  flex-flow: column nowrap;
  max-height: 460px;
  overflow-y: auto;
}
.track {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 5px 0;
  border-top: 1px solid var(--color-primary-light-500-alpha-900, rgba(128, 128, 128, 0.12));
}
.trackText {
  flex: auto;
  min-width: 0;
  p {
    .mixin-ellipsis-1();
  }
}
.trackName {
  font-size: 13px;
  color: var(--color-font);
  span {
    color: var(--color-font-label);
  }
}
p.trackMatch {
  font-size: 11px;
  color: var(--color-font-label);
}
.chip {
  flex: none;
  font-size: 11px;
  padding: 2px 8px;
  border-radius: 10px;
  color: var(--color-font-label);
  background-color: var(--color-primary-background-hover);
  &.found, &.direct {
    color: var(--color-primary-font);
  }
  &.notFound {
    color: #e5484d;
  }
}
.more {
  padding: 6px 0;
}
.retry {
  padding: 0 15px 15px;
  display: flex;
  flex-flow: column nowrap;
  gap: 10px;
  h2 {
    font-size: 14px;
    color: var(--color-font);
    padding-top: 15px;
  }
}
</style>
