// desktop/src/renderer/components/layout/PactModal.vue
<template>
  <material-modal :show="!isAgreePact || isShowPact" max-width="70%" :bg-close="isAgreePact" :close-btn="isAgreePact" @close="handleClose(false)">
    <!-- first run: the language first, the agreement (and what follows) is then in that language -->
    <main v-if="!isAgreePact && !isLanguagePicked" :class="$style.main">
      <h2>Language / 语言</h2>
      <div :class="$style.langs">
        <base-btn v-for="lang in langList" :key="lang.locale" :class="$style.lang" @click="pickLanguage(lang.locale)">{{ lang.name }}</base-btn>
      </div>
    </main>
    <main v-else :class="$style.main">
      <h2>{{ pact.title }}</h2>
      <div class="select scroll" :class="$style.content">
        <template v-if="!isAgreePact"><p><strong>{{ pact.mustAgree }}</strong></p><br></template>
        <template v-for="(paragraph, index) in pact.paragraphs" :key="index">
          <p>
            <strong v-if="paragraph.heading">{{ paragraph.parts[0] }}</strong>
            <template v-else>
              <template v-for="(part, partIndex) in paragraph.parts" :key="partIndex">
                <template v-if="typeof part == 'string'">{{ part }}</template>
                <strong v-else-if="part.bold">{{ part.bold }}</strong>
                <strong v-else class="hover underline" @click="openLink(part.link)">{{ part.text }}</strong>
              </template>
            </template>
          </p><br>
        </template>
        <p v-if="!isAgreePact"><strong>{{ pact.acceptTip }}</strong></p>
      </div>
      <div v-if="!isAgreePact" :class="$style.btns">
        <base-btn :class="$style.btn" @click="handleClose(true)">{{ $t('not_agree') }}</base-btn>
        <base-btn :class="$style.btn" @click="handleAgree">{{ $t('agree') }}</base-btn>
      </div>
    </main>
  </material-modal>
</template>

<script>
import { checkUpdate, quitApp } from '@renderer/utils/ipc'
import { REPO } from '@common/repo'
import { openUrl } from '@common/utils/electron'
import { isShowPact } from '@renderer/store'
import { appSetting, saveAgreePact, updateSetting } from '@renderer/store/setting'
import { computed, ref } from '@common/utils/vueTools'
import { langList } from '@root/lang'
import { getPactText } from '@renderer/utils/pactText'

// The licence agreement (utils/pactText.ts): on first run, after the language is picked
export default {
  setup() {
    const isAgreePact = computed(() => appSetting['common.isAgreePact'])
    const isLanguagePicked = ref(false)
    const pact = computed(() => getPactText(String(appSetting['common.langId'] ?? window.i18n.locale ?? ''), { platform: 'desktop', license: 'agpl' }))

    const pickLanguage = locale => {
      updateSetting({ 'common.langId': locale })
      isLanguagePicked.value = true
    }
    const openLink = link => {
      void openUrl(link == 'license' ? `${REPO}/blob/main/LICENSE` : `${REPO}#readme`)
    }
    const handleAgree = () => {
      saveAgreePact(true)
      checkUpdate()
    }
    const handleClose = isExit => {
      if (isExit) {
        quitApp(true)
        return
      }
      isShowPact.value = false
    }

    return {
      isShowPact,
      isAgreePact,
      isLanguagePicked,
      langList,
      pact,
      pickLanguage,
      openLink,
      handleAgree,
      handleClose,
    }
  },
}
</script>


<style lang="less" module>
@import '@renderer/assets/styles/layout.less';

.main {
  padding: 15px 8px 12px;
  min-width: 200px;
  min-height: 0;
  display: flex;
  flex-flow: column nowrap;
  justify-content: center;
  h2 {
    font-size: 16px;
    color: var(--color-font);
    line-height: 1.3;
    text-align: center;
  }
}

// two columns: the 13 languages fit the window
.langs {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 10px;
  margin: 20px auto 5px;
  width: 380px;
}
.lang {
  display: block;
  width: 100%;
  margin: 0;
}

.content {
  flex: auto;
  margin: 15px 0;
  padding: 0 7px;
  h3 {
    font-weight: bold;
    line-height: 2;
  }
  p {
    line-height: 1.5;
    font-size: 14px;
    text-align: justify;
  }
}

.btns {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.btn {
  display: block;
  width: 48%;
  &:last-child {
    margin-bottom: 0;
  }
}


</style>

// mobile/src/navigation/components/PactModal.tsx
import { useMemo } from 'react'
import { View, ScrollView } from 'react-native'
import { Navigation } from 'react-native-navigation'

import Button from '@/components/common/Button'
import { createStyle, openUrl } from '@/utils/tools'
import { useSettingValue } from '@/store/setting/hook'
import { useTheme } from '@/store/theme/hook'
import Text from '@/components/common/Text'
import ModalContent from './ModalContent'
import { exitApp } from '@/utils/nativeModules/utils'
import { updateSetting } from '@/core/common'
import { checkUpdate } from '@/core/version'
import { initDeeplink } from '@/core/init/deeplink'
import settingState from '@/store/setting/state'
import { REPO } from '@/config/repo'
import { useI18n } from '@/lang'
import { getPactText } from '@/utils/pactText'

const Content = () => {
  const theme = useTheme()
  const t = useI18n()
  // t: changes with the language
  // eslint-disable-next-line react-hooks/exhaustive-deps
  const pact = useMemo(() => getPactText(String(global.i18n.locale ?? ''), { platform: 'mobile', license: 'apache' }), [t])

  const openLink = (link: 'license' | 'repo') => {
    void openUrl(link == 'license' ? 'http://www.apache.org/licenses/LICENSE-2.0' : `${REPO}#readme`)
  }

  const textLinkStyle = {
    ...styles.text,
    textDecorationLine: 'underline',
    color: theme['c-primary-font'],
  } as const

  return (
    <View style={styles.main}>
      <Text style={styles.title} size={18} >{pact.title}</Text>
      <ScrollView style={styles.content} keyboardShouldPersistTaps={'always'}>
        {!settingState.setting['common.isAgreePact'] && <Text selectable style={styles.bold} >{pact.mustAgree}{'\n'}</Text>}
        {
          pact.paragraphs.map((paragraph, index) => (
            <Text key={index} selectable style={paragraph.heading ? styles.bold : styles.text}>
              {
                paragraph.parts.map((part, partIndex) => {
                  if (typeof part == 'string') return part
                  if ('bold' in part) return <Text key={partIndex} style={styles.bold}>{part.bold}</Text>
                  return <Text key={partIndex} onPress={() => { openLink(part.link) }} style={textLinkStyle}>{part.text}</Text>
                })
              }
              {'\n'}
            </Text>
          ))
        }
      </ScrollView>
    </View>
  )
}

// the agreement accepted (on first run): no timer before the button
const Footer = ({ componentId }: { componentId: string }) => {
  const theme = useTheme()
  const t = useI18n()
  const isAgreePact = useSettingValue('common.isAgreePact')
  // t: changes with the language
  // eslint-disable-next-line react-hooks/exhaustive-deps
  const pact = useMemo(() => getPactText(String(global.i18n.locale ?? ''), { platform: 'mobile', license: 'apache' }), [t])

  const handleRejct = () => {
    exitApp()
  }

  const handleConfirm = () => {
    const _isAgreePact = isAgreePact
    if (!isAgreePact) updateSetting({ 'common.isAgreePact': true })
    void Navigation.dismissOverlay(componentId)
    if (!_isAgreePact) {
      void checkUpdate()
      void initDeeplink()
    }
  }

  return (
    <>
      {
        isAgreePact
          ? null
          : (
              <Text selectable style={styles.tip} size={13}>{pact.acceptTip}</Text>
            )
      }
      <View style={styles.btns}>
        {
          isAgreePact
            ? null
            : (
                <Button style={{ ...styles.btn, backgroundColor: theme['c-button-background'] }} onPress={handleRejct}>
                  <Text color={theme['c-button-font']}>{t('pact__decline')}</Text>
                </Button>
              )
        }
        <Button style={{ ...styles.btn, backgroundColor: theme['c-button-background'] }} onPress={handleConfirm}>
          <Text color={theme['c-button-font']}>{isAgreePact ? t('close') : t('pact__accept')}</Text>
        </Button>
      </View>
    </>
  )
}

const PactModal = ({ componentId }: { componentId: string }) => {
  return (
    <ModalContent>
      <Content />
      <Footer componentId={componentId} />
    </ModalContent>
  )
}

const styles = createStyle({
  main: {
    // flexGrow: 0,
    flexShrink: 1,
    marginTop: 15,
    marginBottom: 10,
  },
  content: {
    flexGrow: 0,
    marginLeft: 5,
    marginRight: 5,
    paddingLeft: 10,
    paddingRight: 10,
  },
  title: {
    textAlign: 'center',
    marginBottom: 15,
  },
  part: {
    marginBottom: 10,
  },
  text: {
    fontSize: 14,
    textAlignVertical: 'bottom',
    marginBottom: 5,
  },
  bold: {
    fontSize: 14,
    textAlignVertical: 'bottom',
    fontWeight: 'bold',
  },
  tip: {
    textAlignVertical: 'bottom',
    fontWeight: 'bold',
    paddingLeft: 15,
    paddingRight: 15,
    paddingBottom: 15,
  },
  btns: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingBottom: 15,
    paddingLeft: 15,
    // paddingRight: 15,
  },
  btn: {
    flex: 1,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
    alignItems: 'center',
    borderRadius: 4,
    marginRight: 15,
  },
})

export default PactModal
