// mobile/src/screens/Home/Views/Library/Stats.tsx
import { memo, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { ScrollView, TouchableOpacity, View } from 'react-native'
import Svg, { G, Path, Text as SvgText } from 'react-native-svg'

import {
  STATS_RANGE_IDS, formatClockHour, formatListened, getCalendarWeeks, getClockPieces, getListenStats, getRangeFrom,
  type ListenStats, type StatsRangeId, type StatsTopEntry,
} from '@/utils/listenStats'
import { normalizeArtistName } from '@/utils/artistName'
import { createStyle } from '@/utils/tools'
import { openAlbum } from '@/core/musicLinks'
import { setTempList } from '@/core/list'
import { playList } from '@/core/player/player'
import { LIST_IDS } from '@/config/constant'
import { navigations } from '@/navigation'
import commonState from '@/store/common/state'
import { useTheme } from '@/store/theme/hook'
import { useI18n } from '@/lang'
import Text from '@/components/common/Text'
import Image from '@/components/common/Image'
import { TranslatedText } from '@/components/common/TranslatedText'

// Listening stats (utils/listenStats.ts), like the stats of the history of Nuclear

type TopListId = 'artists' | 'albums' | 'tracks'

const TopList = memo(({ id, title, entries, onPress }: {
  id: TopListId
  title: string
  entries: StatsTopEntry[]
  onPress: (id: TopListId, entry: StatsTopEntry) => void
}) => {
  const theme = useTheme()
  if (!entries.length) return null
  return (
    <View style={{ ...styles.box, backgroundColor: theme['c-primary-light-900-alpha-200'] }}>
      <Text size={16} style={styles.boxTitle}>{title}</Text>
      {
        entries.map((entry, index) => (
          <TouchableOpacity key={entry.key} activeOpacity={0.7} style={styles.topItem} onPress={() => { onPress(id, entry) }}>
            <Text size={12} color={theme['c-font-label']} style={styles.rank}>{index + 1}</Text>
            <Image url={entry.img} style={{ ...styles.topImg, borderRadius: id == 'artists' ? 20 : 6 }} />
            <View style={styles.topText}>
              <Text size={14} numberOfLines={1}><TranslatedText text={entry.name} /></Text>
              {entry.subtitle ? <Text size={12} numberOfLines={1} color={theme['c-font-label']}>{entry.subtitle}</Text> : null}
            </View>
            <Text size={12} color={theme['c-font-label']}>{formatListened(entry.seconds)}</Text>
          </TouchableOpacity>
        ))
      }
    </View>
  )
})

// the hour of the day: a ring of 24 pieces, each one filled as much as it is listened; a piece pressed shows
// its time in the middle
const CLOCK_SIZE = 240
const ListeningClock = memo(({ hours }: { hours: number[] }) => {
  const theme = useTheme()
  const [selected, setSelected] = useState<number | null>(null)
  const pieces = useMemo(() => getClockPieces(hours, 38, 94), [hours])
  return (
    <View style={{ width: CLOCK_SIZE, height: CLOCK_SIZE, alignSelf: 'center' }}>
      <Svg width={CLOCK_SIZE} height={CLOCK_SIZE} viewBox="-115 -115 230 230">
        {
          pieces.map(piece => (
            <G key={piece.hour} onPress={() => { setSelected(selected == piece.hour ? null : piece.hour) }}>
              {piece.fill ? <Path d={piece.fill} fill={theme['c-primary']} /> : null}
              <Path
                d={piece.outline} fill="transparent"
                stroke={piece.hour == selected ? theme['c-primary'] : theme['c-font']}
                strokeOpacity={piece.hour == selected ? 1 : 0.6} strokeWidth={piece.hour == selected ? 1.8 : 1}
              />
            </G>
          ))
        }
        {
          [0, 6, 12, 18].map(hour => (
            <SvgText key={hour} x={Math.sin(hour * Math.PI / 12) * 106} y={-Math.cos(hour * Math.PI / 12) * 106 + 4} fontSize={11} fontWeight="bold" fill={theme['c-font']} textAnchor="middle">
              {String(hour).padStart(2, '0')}
            </SvgText>
          ))
        }
      </Svg>
      {
        // the hour pressed and its time (nothing when no hour is pressed)
        selected == null
          ? null
          : (
              <View pointerEvents="none" style={styles.clockCenter}>
                <Text size={10} numberOfLines={1}>{formatClockHour(selected)}</Text>
                <Text size={13} style={styles.bold}>{formatListened(hours[selected])}</Text>
              </View>
            )
      }
    </View>
  )
})

const WeekChart = memo(({ weekdays, names }: { weekdays: number[], names: string[] }) => {
  const theme = useTheme()
  const max = Math.max(1, ...weekdays)
  return (
    <View style={styles.week}>
      {
        weekdays.map((value, index) => (
          <View key={index} style={styles.weekCol}>
            <Text size={9} color={theme['c-font-label']} numberOfLines={1}>{value ? formatListened(value) : ''}</Text>
            <View style={styles.weekTrack}>
              <View style={{ ...styles.weekBar, height: `${Math.max(1.5, value / max * 100)}%`, backgroundColor: theme['c-primary'] }} />
            </View>
            <Text size={11} color={theme['c-font-label']}>{names[index]}</Text>
          </View>
        ))
      }
    </View>
  )
})

// the calendar of the last year: a column a week, a cell a day, darker the more it is listened
const CELL = 11
const CELL_GAP = 3
const LEVEL_OPACITY = [0.1, 0.3, 0.5, 0.75, 1]
const Calendar = memo(({ days, less, more }: { days: Record<string, number>, less: string, more: string }) => {
  const theme = useTheme()
  const weeks = useMemo(() => getCalendarWeeks(), [])
  const maxDay = Math.max(1, ...Object.values(days))
  const level = (seconds: number) => seconds ? Math.min(4, Math.ceil(seconds / maxDay * 4)) : 0
  const scrollRef = useRef<ScrollView>(null)
  const months: Array<{ index: number, name: string }> = []
  let lastMonth = -1
  weeks.forEach((week, index) => {
    const first = week.find(day => day)
    if (!first || first.date.getMonth() == lastMonth) return
    lastMonth = first.date.getMonth()
    if (index == 0 && first.date.getDate() > 7) return
    months.push({ index, name: first.date.toLocaleDateString(undefined, { month: 'short' }) })
  })
  return (
    <>
      <ScrollView ref={scrollRef} horizontal showsHorizontalScrollIndicator={false} onContentSizeChange={() => scrollRef.current?.scrollToEnd({ animated: false })}>
        <View>
          <View style={{ height: 14 }}>
            {
              months.map(month => (
                <Text key={month.index} size={9} color={theme['c-font-label']} style={{ position: 'absolute', left: month.index * (CELL + CELL_GAP) }}>{month.name}</Text>
              ))
            }
          </View>
          <View style={styles.calendarWeeks}>
            {
              weeks.map((week, w) => (
                <View key={w} style={styles.calendarWeek}>
                  {
                    week.map((day, d) => (
                      <View key={d} style={{ width: CELL, height: CELL, borderRadius: 2, backgroundColor: day ? theme['c-primary'] : 'transparent', opacity: day ? LEVEL_OPACITY[level(days[day.key] ?? 0)] : 0 }} />
                    ))
                  }
                </View>
              ))
            }
          </View>
        </View>
      </ScrollView>
      <View style={styles.legend}>
        <Text size={11} color={theme['c-font-label']}>{less}</Text>
        {LEVEL_OPACITY.map(opacity => <View key={opacity} style={{ width: CELL, height: CELL, borderRadius: 2, backgroundColor: theme['c-primary'], opacity }} />)}
        <Text size={11} color={theme['c-font-label']}>{more}</Text>
      </View>
    </>
  )
})

export default () => {
  const t = useI18n()
  const theme = useTheme()
  const [rangeId, setRangeId] = useState<StatsRangeId>('last30Days')
  const [stats, setStats] = useState<ListenStats | null>(null)

  useEffect(() => {
    let isActive = true
    void getListenStats(getRangeFrom(rangeId)).then(result => {
      if (isActive) setStats(result)
    })
    return () => {
      isActive = false
    }
  }, [rangeId])

  // Monday first
  const weekdayNames = useMemo(() => Array.from({ length: 7 }, (_, index) => new Date(2024, 0, 1 + index).toLocaleDateString(undefined, { weekday: 'short' })), [])

  const handleEntryPress = useCallback((id: TopListId, entry: StatsTopEntry) => {
    switch (id) {
      case 'artists':
        navigations.pushCollectionScreen(commonState.componentIds.home!, { type: 'artist', name: normalizeArtistName(entry.name), fromSource: entry.musicInfo.source })
        break
      case 'albums':
        void openAlbum(entry.musicInfo)
        break
      case 'tracks':
        void setTempList('stats_track', [entry.musicInfo as LX.Music.MusicInfoOnline]).then(() => { void playList(LIST_IDS.TEMP, 0) })
        break
    }
  }, [])

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.ranges}>
        {
          STATS_RANGE_IDS.map(id => (
            <TouchableOpacity key={id} activeOpacity={0.7} onPress={() => { setRangeId(id) }}>
              <Text
                size={13} color={id == rangeId ? theme['c-font'] : theme['c-font-label']}
                style={{ ...styles.rangeBtn, fontWeight: id == rangeId ? 'bold' : 'normal', backgroundColor: id == rangeId ? theme['c-primary-light-400-alpha-700'] : 'transparent' }}
              >{t(`stats__range_${id}`)}</Text>
            </TouchableOpacity>
          ))
        }
      </ScrollView>
      {
        !stats
          ? null
          : stats.firstPlay == null
            ? <Text color={theme['c-font-label']} style={styles.empty}>{t('stats__empty')}</Text>
            : (
                <>
                  <View style={styles.summary}>
                    <View>
                      <Text size={22} style={styles.bold} color={theme['c-primary-font']}>{formatListened(stats.seconds)}</Text>
                      <Text size={12} color={theme['c-font-label']}>{t('stats__listening_time')}</Text>
                    </View>
                    <View>
                      <Text size={22} style={styles.bold} color={theme['c-primary-font']}>{stats.plays}</Text>
                      <Text size={12} color={theme['c-font-label']}>{t('stats__plays')}</Text>
                    </View>
                  </View>
                  <TopList id="artists" title={t('stats__top_artists')} entries={stats.topArtists} onPress={handleEntryPress} />
                  <TopList id="albums" title={t('stats__top_albums')} entries={stats.topAlbums} onPress={handleEntryPress} />
                  <TopList id="tracks" title={t('stats__top_tracks')} entries={stats.topTracks} onPress={handleEntryPress} />
                  {
                    stats.plays
                      ? (
                          <>
                            <View style={{ ...styles.box, backgroundColor: theme['c-primary-light-900-alpha-200'] }}>
                              <Text size={16} style={styles.boxTitle}>{t('stats__hour_of_day')}</Text>
                              <ListeningClock hours={stats.hours} />
                            </View>
                            <View style={{ ...styles.box, backgroundColor: theme['c-primary-light-900-alpha-200'] }}>
                              <Text size={16} style={styles.boxTitle}>{t('stats__day_of_week')}</Text>
                              <WeekChart weekdays={stats.weekdays} names={weekdayNames} />
                            </View>
                          </>
                        )
                      : null
                  }
                  <View style={{ ...styles.box, backgroundColor: theme['c-primary-light-900-alpha-200'] }}>
                    <Text size={16} style={styles.boxTitle}>{t('stats__calendar')}</Text>
                    <Calendar days={stats.days} less={t('stats__less')} more={t('stats__more')} />
                  </View>
                </>
              )
      }
    </ScrollView>
  )
}

const styles = createStyle({
  container: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 14,
    paddingBottom: 24,
    gap: 14,
  },
  ranges: {
    gap: 6,
    paddingVertical: 4,
  },
  rangeBtn: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 15,
    overflow: 'hidden',
  },
  empty: {
    textAlign: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  summary: {
    flexDirection: 'row',
    gap: 30,
  },
  bold: {
    fontWeight: 'bold',
  },
  box: {
    borderRadius: 12,
    padding: 12,
  },
  boxTitle: {
    fontWeight: 'bold',
    marginBottom: 8,
  },
  topItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 5,
  },
  rank: {
    width: 18,
    textAlign: 'right',
  },
  topImg: {
    width: 40,
    height: 40,
  },
  topText: {
    flex: 1,
    minWidth: 0,
  },
  clockCenter: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  week: {
    height: 170,
    flexDirection: 'row',
    gap: 8,
  },
  weekCol: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
  },
  weekTrack: {
    flex: 1,
    width: '100%',
    justifyContent: 'flex-end',
  },
  weekBar: {
    width: '100%',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
  },
  calendarWeeks: {
    flexDirection: 'row',
    gap: CELL_GAP,
  },
  calendarWeek: {
    gap: CELL_GAP,
  },
  legend: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 4,
    marginTop: 8,
  },
})

// desktop/src/renderer/views/Stats/index.vue
<template>
  <div :class="[$style.container, 'scroll']">
    <div :class="$style.header">
      <h2 :class="$style.title">{{ $t('stats__title') }}</h2>
      <span :class="$style.rangeDates">{{ rangeDates }}</span>
      <div :class="$style.ranges">
        <button
          v-for="id in STATS_RANGE_IDS" :key="id" type="button"
          :class="[$style.rangeBtn, { [$style.active]: id == rangeId }]" @click="rangeId = id"
        >
          {{ $t(`stats__range_${id}`) }}
        </button>
      </div>
    </div>

    <material-empty v-if="loaded && view.firstPlay == null" :label="$t('stats__empty')" />
    <template v-else-if="loaded">
      <div :class="$style.summary">
        <div><strong>{{ formatListened(view.seconds) }}</strong><span>{{ $t('stats__listening_time') }}</span></div>
        <div><strong>{{ view.plays }}</strong><span>{{ $t('stats__plays') }}</span></div>
      </div>

      <div v-if="view.plays" :class="$style.tops">
        <section v-for="list in topLists" :key="list.id" :class="$style.box">
          <h3>{{ list.title }}</h3>
          <ol :class="$style.topList">
            <li v-for="(entry, index) in list.entries" :key="entry.key" :class="$style.topItem" @click="openEntry(list.id, entry)">
              <span :class="$style.rank">{{ index + 1 }}</span>
              <div :class="[$style.topImg, { [$style.round]: list.id == 'artists' }]"><base-image :src="entry.img" :icon="list.id == 'artists' ? 'dj' : 'albums'" /></div>
              <div :class="$style.topText">
                <p :class="$style.topName"><common-translatable-text :text="entry.name" /></p>
                <p v-if="entry.subtitle" :class="$style.topSub">{{ entry.subtitle }}</p>
              </div>
              <span :class="$style.topValue">{{ formatListened(entry.seconds) }}</span>
            </li>
            <!-- the lists are as long as the longest one: empty slots -->
            <li v-for="index in topSlots - list.entries.length" :key="`empty_${index}`" :class="[$style.topItem, $style.topEmpty]" aria-hidden="true" />
          </ol>
        </section>
      </div>

      <div v-if="view.plays" :class="$style.charts">
        <section :class="[$style.box, $style.clockBox]">
          <h3>{{ $t('stats__hour_of_day') }}</h3>
          <svg :class="$style.clock" viewBox="-112 -112 224 224" @mouseleave="hoveredHour = null">
            <g v-for="piece in clockPieces" :key="piece.hour" :class="$style.clockPiece" @mouseenter="hoveredHour = piece.hour">
              <path v-if="piece.fill" :d="piece.fill" :class="$style.clockFill" />
              <path :d="piece.outline" :class="[$style.clockOutline, { [$style.clockHover]: piece.hour == hoveredHour }]" />
            </g>
            <text v-for="hour in [0, 6, 12, 18]" :key="hour" :class="$style.clockLabel" :x="Math.sin(hour * Math.PI / 12) * 104" :y="-Math.cos(hour * Math.PI / 12) * 104 + 4">{{ String(hour).padStart(2, '0') }}</text>
            <text :class="$style.clockCenterLabel" y="-5">{{ clockCenter.label }}</text>
            <text :class="$style.clockCenterValue" y="11">{{ clockCenter.value }}</text>
          </svg>
        </section>
        <section :class="[$style.box, $style.weekBox]">
          <h3>{{ $t('stats__day_of_week') }}</h3>
          <div :class="$style.week">
            <div v-for="(value, index) in weekdays" :key="index" :class="$style.weekCol" :title="formatListened(value)">
              <span :class="$style.weekValue">{{ value ? formatListened(value) : '' }}</span>
              <div :class="$style.weekTrack"><div :class="$style.weekBar" :style="{ height: `${maxWeekday ? value / maxWeekday * 100 : 0}%` }" /></div>
              <span :class="$style.weekLabel">{{ weekdayNames[index] }}</span>
            </div>
          </div>
        </section>
      </div>

      <section :class="[$style.box, $style.calendarBox]">
        <h3>{{ $t('stats__calendar') }}</h3>
        <svg :class="$style.calendar" :viewBox="`0 0 ${calendar.width} ${calendar.height}`">
          <text v-for="month in calendar.months" :key="month.x" :class="$style.calendarLabel" :x="month.x" y="9">{{ month.name }}</text>
          <text v-for="(name, index) in weekdayNames" v-show="index % 2 == 0" :key="name" :class="$style.calendarLabel" x="0" :y="CAL_TOP + index * CAL_STEP + 9">{{ name }}</text>
          <template v-for="(week, w) in calendar.weeks" :key="w">
            <rect
              v-for="(day, d) in week" v-show="day" :key="d"
              :x="CAL_LEFT + w * CAL_STEP" :y="CAL_TOP + d * CAL_STEP" :width="CAL_CELL" :height="CAL_CELL" rx="2"
              :class="$style.calendarCell" :fill-opacity="day ? levelOpacity(days[day.key] ?? 0) : 0"
            >
              <title v-if="day">{{ day.date.toLocaleDateString() }} · {{ formatListened(days[day.key] ?? 0) }}</title>
            </rect>
          </template>
        </svg>
        <div :class="$style.legend">
          <span>{{ $t('stats__less') }}</span>
          <svg v-for="level in [0, 1, 2, 3, 4]" :key="level" viewBox="0 0 10 10" width="11" height="11"><rect width="10" height="10" rx="2" :class="$style.calendarCell" :fill-opacity="LEVEL_OPACITY[level]" /></svg>
          <span>{{ $t('stats__more') }}</span>
        </div>
      </section>
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, shallowRef, watch, onMounted } from '@common/utils/vueTools'
import { useRouter } from '@common/utils/vueRouter'
import { useI18n } from '@renderer/plugins/i18n'
import { setTempList } from '@renderer/store/list/action'
import { playList } from '@renderer/core/player/action'
import { LIST_IDS } from '@common/constants'
import { isSecondarySource } from '@renderer/utils/secondarySources'
import { openSecondarySongAlbum } from '@renderer/utils/songLinks'
import { normalizeArtistName } from '@renderer/utils/artistName'
import {
  STATS_RANGE_IDS, formatClockHour, formatListened, getCalendarWeeks, getClockPieces, getListenStats, getRangeFrom,
  type ListenStats, type StatsRangeId, type StatsTopEntry,
} from '@renderer/utils/listenStats'

// Listening stats (utils/listenStats.ts), like the stats of the history of Nuclear

const t = useI18n()
const router = useRouter()
const rangeId = ref<StatsRangeId>('last30Days')
const stats = shallowRef<ListenStats | null>(null)
const loaded = computed(() => !!stats.value)
// the stats shown (empty ones until they are loaded)
const EMPTY_STATS: ListenStats = { from: 0, to: 0, seconds: 0, plays: 0, topArtists: [], topAlbums: [], topTracks: [], hours: Array<number>(24).fill(0), weekdays: Array<number>(7).fill(0), days: {}, firstPlay: null }
const view = computed(() => stats.value ?? EMPTY_STATS)

const load = async() => {
  const result = await getListenStats(getRangeFrom(rangeId.value))
  stats.value = result
}
watch(rangeId, () => { void load() })
onMounted(() => { void load() })

const rangeDates = computed(() => {
  if (!stats.value) return ''
  const from = stats.value.from ? stats.value.from : stats.value.firstPlay ?? stats.value.to
  return `${new Date(from * 1000).toLocaleDateString()} – ${new Date(stats.value.to * 1000).toLocaleDateString()}`
})

const topLists = computed(() => stats.value
  ? [
      { id: 'artists', title: t('stats__top_artists'), entries: stats.value.topArtists },
      { id: 'albums', title: t('stats__top_albums'), entries: stats.value.topAlbums },
      { id: 'tracks', title: t('stats__top_tracks'), entries: stats.value.topTracks },
    ]
  : [])

const topSlots = computed(() => Math.max(0, ...topLists.value.map(list => list.entries.length)))

const ONLINE_SOURCES = ['kw', 'wy', 'tx', 'kg', 'mg']
const openEntry = (listId: string, entry: StatsTopEntry) => {
  const musicInfo = entry.musicInfo
  switch (listId) {
    case 'artists':
      void router.push({ path: '/artist', query: { name: normalizeArtistName(entry.name), source: musicInfo.source } })
      break
    case 'albums': {
      if (isSecondarySource(musicInfo.source)) {
        void openSecondarySongAlbum(router, musicInfo)
        break
      }
      const albumId = (musicInfo.meta as { albumId?: string | number }).albumId
      if (ONLINE_SOURCES.includes(musicInfo.source) && albumId) void router.push({ path: '/album', query: { source: musicInfo.source, id: String(albumId), name: entry.name } })
      break
    }
    case 'tracks':
      void setTempList('stats_track', [musicInfo as LX.Music.MusicInfoOnline]).then(() => { playList(LIST_IDS.TEMP, 0) })
      break
  }
}

// the hour of the day: a ring of 24 pieces, each one filled as much as it is listened (its time shown on hover)
const hoveredHour = ref<number | null>(null)
const clockPieces = computed(() => getClockPieces(view.value.hours, 36, 92))
// the text in the middle: the hour hovered and its time (nothing when no hour is hovered)
const clockCenter = computed(() => {
  const hour = hoveredHour.value
  return hour == null
    ? { label: '', value: '' }
    : { label: formatClockHour(hour), value: formatListened(view.value.hours[hour]) }
})

// Monday first
const weekdayNames = computed(() => Array.from({ length: 7 }, (_, index) => new Date(2024, 0, 1 + index).toLocaleDateString(undefined, { weekday: 'short' })))
const weekdays = computed(() => stats.value?.weekdays ?? [])
const maxWeekday = computed(() => Math.max(0, ...weekdays.value))
const days = computed(() => stats.value?.days ?? {})

// the calendar of the last year: a column a week, a cell a day, darker the more it is listened
const CAL_CELL = 11
const CAL_STEP = 14
const CAL_LEFT = 30
const CAL_TOP = 16
const LEVEL_OPACITY = [0.08, 0.3, 0.5, 0.75, 1]
const calendar = computed(() => {
  const weeks = getCalendarWeeks()
  const months: Array<{ x: number, name: string }> = []
  let lastMonth = -1
  weeks.forEach((week, index) => {
    const first = week.find(day => day)
    if (!first || first.date.getMonth() == lastMonth) return
    lastMonth = first.date.getMonth()
    // no label on the first column when the month starts at its end (the labels would overlap)
    if (index == 0 && first.date.getDate() > 7) return
    months.push({ x: CAL_LEFT + index * CAL_STEP, name: first.date.toLocaleDateString(undefined, { month: 'short' }) })
  })
  return { weeks, months, width: CAL_LEFT + weeks.length * CAL_STEP, height: CAL_TOP + 7 * CAL_STEP }
})
// the levels of the days: by quarters of the most listened day of the year
const maxDay = computed(() => Math.max(1, ...Object.values(days.value)))
const levelOpacity = (seconds: number) => {
  if (!seconds) return LEVEL_OPACITY[0]
  return LEVEL_OPACITY[Math.min(4, Math.ceil(seconds / maxDay.value * 4))]
}
</script>

<style lang="less" module>
@import '@renderer/assets/styles/layout.less';

.container {
  height: 100%;
  padding: 15px 18px 25px;
  display: flex;
  flex-flow: column nowrap;
  gap: 16px;
}
// (the sections keep their size: the page scrolls)
.container > * {
  flex: none;
}

.header {
  display: flex;
  align-items: center;
  gap: 12px;
  flex-wrap: wrap;
}
.title {
  font-size: 18px;
  color: var(--color-font);
  flex: auto;
}
.rangeDates {
  font-size: 12px;
  color: var(--color-font-label);
}
.ranges {
  display: flex;
  gap: 4px;
}
.rangeBtn {
  border: none;
  background: transparent;
  padding: 4px 9px;
  border-radius: 12px;
  font-size: 12px;
  color: var(--color-font-label);
  cursor: pointer;
  &:hover {
    color: var(--color-font);
  }
  &.active {
    color: var(--color-primary-font);
    background-color: var(--color-primary-background-hover);
  }
}

.summary {
  display: flex;
  gap: 30px;
  > div {
    display: flex;
    flex-flow: column nowrap;
    gap: 2px;
  }
  strong {
    font-size: 22px;
    color: var(--color-primary-font);
  }
  span {
    font-size: 12px;
    color: var(--color-font-label);
  }
}

.box {
  border-radius: 8px;
  padding: 12px 14px;
  background-color: var(--color-primary-light-100-alpha-700);
  min-width: 0;
  h3 {
    font-size: 14px;
    color: var(--color-font);
    margin-bottom: 10px;
  }
}

.tops {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
  gap: 14px;
  align-items: start;
}
.topList {
  display: flex;
  flex-flow: column nowrap;
  gap: 4px;
}
.topItem {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 3px 4px;
  border-radius: 6px;
  cursor: pointer;
  transition: background-color @transition-normal;
  &:hover {
    background-color: var(--color-primary-background-hover);
  }
}
.rank {
  width: 16px;
  flex: none;
  text-align: right;
  font-size: 12px;
  color: var(--color-font-label);
}
.topImg {
  width: 34px;
  height: 34px;
  flex: none;
  overflow: hidden;
  border-radius: 4px;
  :global(img) {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
}
.round {
  border-radius: 50%;
}
.topText {
  flex: auto;
  min-width: 0;
}
.topName {
  font-size: 13px;
  color: var(--color-font);
  .mixin-ellipsis-1();
}
.topSub {
  font-size: 11px;
  color: var(--color-font-label);
  .mixin-ellipsis-1();
}
.topEmpty {
  // as high as an entry (its picture and padding)
  height: 40px;
  cursor: default;
  &:hover {
    background-color: transparent;
  }
}
.topValue {
  flex: none;
  font-size: 12px;
  color: var(--color-font-label);
}

.charts {
  display: flex;
  gap: 14px;
  flex-wrap: wrap;
}
.clockBox {
  flex: none;
}
.clock {
  width: 240px;
  height: 240px;
  display: block;
}
.clockPiece {
  cursor: default;
}
.clockOutline {
  fill: transparent;
  stroke: var(--color-font);
  stroke-opacity: 0.6;
  stroke-width: 1;
  transition: stroke-opacity @transition-normal;
}
.clockHover {
  stroke: var(--color-primary);
  stroke-opacity: 1;
  stroke-width: 1.4;
}
.clockFill {
  fill: var(--color-primary);
}
.clockLabel {
  font-size: 11px;
  font-weight: bold;
  fill: var(--color-font);
  text-anchor: middle;
}
.clockCenterLabel {
  font-size: 8px;
  fill: var(--color-font);
  text-anchor: middle;
}
.clockCenterValue {
  font-size: 11px;
  font-weight: bold;
  fill: var(--color-font);
  text-anchor: middle;
}
.weekBox {
  flex: 1 1 300px;
  display: flex;
  flex-flow: column nowrap;
}
.week {
  flex: auto;
  min-height: 200px;
  display: flex;
  gap: 10px;
}
.weekCol {
  flex: 1;
  display: flex;
  flex-flow: column nowrap;
  align-items: center;
  gap: 4px;
}
.weekValue {
  font-size: 10px;
  color: var(--color-font-label);
  white-space: nowrap;
}
.weekTrack {
  flex: auto;
  width: 100%;
  max-width: 34px;
  display: flex;
  align-items: flex-end;
}
.weekBar {
  width: 100%;
  min-height: 2px;
  border-radius: 4px 4px 0 0;
  background-color: var(--color-primary);
}
.weekLabel {
  font-size: 11px;
  color: var(--color-font-label);
}

.calendarBox {
  overflow-x: auto;
}
.calendar {
  display: block;
  width: 100%;
  min-width: 700px;
  height: auto;
}
.calendarLabel {
  font-size: 9px;
  fill: var(--color-font-label);
}
.calendarCell {
  fill: var(--color-primary);
}
.legend {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: 4px;
  margin-top: 6px;
  font-size: 11px;
  color: var(--color-font-label);
}
</style>
